### ISSUE TITLE
Looping Update

### ISSUE THREAD

**Issue by gmccauley** [jonfairbanks/OctoPrint-NetworkHealth#13]
Looks like the metadata for this plugin is still 1.0.0 so even though installed or updated to 1.0.2, it's constantly asking to install an update.

**Comment by jonfairbanks** [comment]
Gah, newb mistake. Patched this in 1.0.3.

https://github.com/jonfairbanks/OctoPrint-NetworkHealth/releases/tag/1.0.3

Thanks for the callout.

**Comment by gmccauley** [comment]
Confirmed.  Great Plugin!
