### ISSUE TITLE
Network Health plugin is causing permanent high load while enabled

### ISSUE THREAD

**Issue by NMe84** [jonfairbanks/OctoPrint-NetworkHealth#18]
I was having issues with my Pi overheating and I just dove into the cause. Turns out the Pi (a 3B+) had a permanent load of 2.5 _when idle_. Turning on safe mode resolved that issue so I looked into my plugins. I uninstalled one of the non-stock plugins that I was using but it didn't fix anything, so I only had the Network Health plugin left to check, and sure enough, disabling it gave me normal load levels.

This was before I turned off the Network Health plugin:  
![image](https://user-images.githubusercontent.com/4869296/162430046-64651d8a-ae66-4da6-8a26-1706608c5255.png)

This was after:  
![image](https://user-images.githubusercontent.com/4869296/162430101-f493de8c-4ff6-4520-a80b-12c6406b733a.png)

Literally the only difference between the two is whether or not Network Health is enabled.

I should probably add that I did properly install the plugin including the sudoers configuation, unless there is more to it than the readme suggests.

**Comment by jonfairbanks** [comment]
Hello, thanks for the report. Could you share your octoprint.log so I can take a closer look?

https://community.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299

**Comment by NMe84** [comment]
I can, but from what I can tell it sadly doesn't say anything interesting: [octoprint.log](https://github.com/jonfairbanks/OctoPrint-NetworkHealth/files/8455634/octoprint.log)

Over the duration of this log file I first had two plugins installed (Octolapse and Network Health) and I uninstalled Octolapse, then went through the process described above and disabled Network Health.

**Comment by NMe84** [comment]
I think it's safe to close this ticket. While my initial testing seemed to indicate it was the plugin, I think Octoprint may have been doing something in the background that just happened to stop right around the time I stopped the plugin. Sorry for wasting your time.

**Comment by jonfairbanks** [comment]
No worries, thanks for reporting back!
